---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu
  - name: centos

suites:
  - name: default
    run_list:
      - recipe[roswell]
  - name: branch
    run_list:
      - recipe[roswell]
    attributes:
      roswell:
        branch: "master"
  - name: user
    run_list:
      - recipe[roswell]
    attributes:
      roswell:
        user: "kitchen"
  - name: prefix
    run_list:
      - recipe[roswell]
    attributes:
      roswell:
        prefix: "/opt/local"
  - name: version
    run_list:
      - recipe[roswell]
    attributes:
      roswell:
        version: "sbcl"
